on:
  workflow_dispatch:
    inputs:
      name:
        description: "Argo workflow name"
        required: true
name: Pull Collected Data
jobs:
  build:
    name: Create PR for api file
    runs-on: ubuntu-latest
    steps:
      # Install minio
      - name: Create bin dir
        run: |
          mkdir -p /tmp/bin
          echo "::add-path::/tmp/bin"
      - name: Install minio
        run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc -L -o /tmp/bin/mc
      - name: Install argo
        run: |
          curl https://github.com/argoproj/argo/releases/download/v2.9.3/argo-linux-amd64 -L -o /tmp/bin/argo
      - name: Make bin executable
        run: chmod +x /tmp/bin/*
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save python-record-api
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pip-

      - name: Install flit
        run: |
          python -m pip install --upgrade pip
          pip install flit
      # Clone repo
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install package
        run: flit install

      - name: Set argo namespace
        working-directory: ./k8
        run: make k8-argo-default
      # Fetch file
      - name: Fetch file
        run: env MC_HOST_artifact=${{ secrets.S3_HOST }} make WORKFLOW_NAME=${{ github.event.inputs.name }} download-workflow
        working-directory: ./k8
      # Push file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: |
            [Bot] Add API from ${{ github.event.inputs.name }}
          title: |
            [Bot] Add API from ${{ github.event.inputs.name }}
          branch: bot-${{ github.event.inputs.name }}
          body: |
            Pull API generatd by Argo Workflow
            [`${{ github.event.inputs.name }}`](http://167.172.14.45:2746/workflows/argo/${{ github.event.inputs.name }})
